/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FundraisingStorage } from "./FundraisingStorage";
export type { ShareVaultStorage } from "./ShareVaultStorage";
