/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWalletCallbacks,
  IWalletCallbacksInterface,
} from "../../../contracts/interface/IWalletCallbacks";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "cleartexts",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "decryptionProof",
        type: "bytes",
      },
    ],
    name: "callbackCheckSufficientBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "cleartexts",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "decryptionProof",
        type: "bytes",
      },
    ],
    name: "callbackDecryptAvailableBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWalletCallbacks__factory {
  static readonly abi = _abi;
  static createInterface(): IWalletCallbacksInterface {
    return new Interface(_abi) as IWalletCallbacksInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWalletCallbacks {
    return new Contract(address, _abi, runner) as unknown as IWalletCallbacks;
  }
}
