/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FundraisingStorage__factory } from "./FundraisingStorage__factory";
export { ShareVaultStorage__factory } from "./ShareVaultStorage__factory";
