/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ShareVaultStorage,
  ShareVaultStorageInterface,
} from "../../../contracts/storage/ShareVaultStorage";

const _abi = [
  {
    inputs: [],
    name: "CACHE_TIMEOUT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "campaignContract",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ShareVaultStorage__factory {
  static readonly abi = _abi;
  static createInterface(): ShareVaultStorageInterface {
    return new Interface(_abi) as ShareVaultStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ShareVaultStorage {
    return new Contract(address, _abi, runner) as unknown as ShareVaultStorage;
  }
}
