/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as decryptionCallbackSol from "./DecryptionCallback.sol";
export type { decryptionCallbackSol };
